### ISSUE TITLE
Spell Error

### ISSUE THREAD

**Issue by yonghenghuanmie** [VirusTotal/c-vtapi#11]
When I compile this code on windows,I found a spell error on VtObject.h line 56,it should be "INFINITE".

**Comment by aurora-of-earth** [comment]
@yonghenghuanmie No problem when compiling on Linux.
It has to be a problem from your build environment.

**Comment by yonghenghuanmie** [comment]
> 
> 
> @yonghenghuanmie No problem when compiling on Linux.
> It has to be a problem from your build environment.

Please read my comments carefully,"on windows"
